# **Processamento de Imagens e Imagens**
Engenharia da Computação - 2021.01

## Reconhecimento de Padrões

### Download das imagens de teste

### Imports

In [38]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

### Code

In [39]:
# carregar o arquivo com as caracteristicas
df = pd.read_csv('drive/MyDrive/Colab Notebooks/College/Signal-Image-Processing/image_dataset_publico/iris_dataset.csv', sep=';')
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [40]:
#separar as caracteristicas e os rótulos
X = df.iloc[:, 0:4]     # caracteristicas 
y = df.iloc[:, 4]       # rotulos
print(y)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object


In [41]:
# PRE-PROCESSAMENTO
normalizar = StandardScaler()
normalizar.fit(X)
X = normalizar.transform(X)
print(X[:5])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


In [42]:
# PROCESSAMENTO
# Dividir o conjunto de dados em treinamento (TRAIN) e teste (TEST)
XTrain, XTest, yTrain, yTest = train_test_split(X, y, test_size=0.30, random_state=35)

In [43]:
# CLASSIFICADOR
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(XTrain, yTrain)
Y = knn.predict(XTest)

In [44]:
# RESULTADO
acc = accuracy_score(yTest, Y)
print(f'Accuracia {acc:.2f}')

Accuracia 0.93


In [45]:
# Matriz confusao
print(pd.crosstab(yTest, Y, rownames=['True'], colnames=['Predicao'], margins=True))

Predicao         Iris-setosa  Iris-versicolor  Iris-virginica  All
True                                                              
Iris-setosa               16                0               0   16
Iris-versicolor            0               13               1   14
Iris-virginica             0                2              13   15
All                       16               15              14   45


### Exercises

#### Imports

#### Code